// VideoGrab - popup-cookies.js
// Browser cookie extraction, Netscape format helpers, and cookie status UI

function countCookies(cookieText) {
  if (!cookieText) return 0;
  return cookieText.split('\n').filter(line => {
    const t = line.trim();
    return t && !t.startsWith('#');
  }).length;
}

/** Build Netscape cookie file content from a chrome.cookies array */
function buildNetscapeCookies(cookies, sourceLabel) {
  if (!cookies || cookies.length === 0) return '';
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by VideoGrab',
    `# Source: ${sourceLabel}`
  ];
  cookies.forEach(c => {
    const flag  = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path  = c.path || '/';
    const sec   = c.secure ? 'TRUE' : 'FALSE';
    const exp   = c.expirationDate ? Math.round(c.expirationDate) : 0;
    const prefix = c.httpOnly ? '#HttpOnly_' : '';
    lines.push(`${prefix}${c.domain}\t${flag}\t${path}\t${sec}\t${exp}\t${c.name}\t${c.value}`);
  });
  return lines.join('\n');
}

/** Extract all cookies for a full URL (including HttpOnly via chrome.cookies API) */
async function extractBrowserCookies(pageUrl) {
  if (!pageUrl || !pageUrl.startsWith('http')) return '';
  return new Promise((resolve) => {
    try {
      chrome.cookies.getAll({ url: pageUrl }, (cookies) => {
        resolve(buildNetscapeCookies(cookies || [], pageUrl));
      });
    } catch (e) {
      console.error('[Cookies] extractBrowserCookies error:', e);
      resolve('');
    }
  });
}

/** Extract cookies for a domain pattern (wildcard glob like *.youtube.com) */
async function extractBrowserCookiesForDomain(domainPattern) {
  if (!domainPattern) return '';
  let domain = domainPattern.trim().toLowerCase();
  if (domain.startsWith('*.')) domain = domain.substring(2);
  return new Promise((resolve) => {
    try {
      chrome.cookies.getAll({ domain }, (cookies) => {
        resolve(buildNetscapeCookies(cookies || [], domainPattern));
      });
    } catch (e) {
      console.error('[Cookies] extractBrowserCookiesForDomain error:', e);
      resolve('');
    }
  });
}

/** Refresh the live cookies snapshot for the active tab */
async function refreshLiveCookiesState() {
  if (!activeTabUrl || !activeTabUrl.startsWith('http')) {
    return;
  }
  liveCookiesText = await extractBrowserCookies(activeTabUrl);
}

/** Check live cookies for the profile modal's domain pattern */
async function checkModalDomainCookies(pattern) {
  const el = elements.profLiveCookieStatus;
  if (!el) return;
  const txt = el.querySelector('.cookie-status-text');
  if (!pattern) {
    el.className = 'cookie-status-indicator';
    txt.innerText = 'Enter a domain pattern to check';
    return;
  }
  const cookies = await extractBrowserCookiesForDomain(pattern);
  const count = countCookies(cookies);
  el.className = 'cookie-status-indicator';
  if (count > 0) {
    el.classList.add('has-cookies');
    txt.innerText = `${count} live cookies available in browser`;
  } else {
    el.classList.add('no-cookies');
    txt.innerText = 'No live cookies found in browser for this domain';
  }
}

/** Get the cookies to pass to a download job, prioritizing custom profile overrides, then falling back to live browser cookies for the video's domain */
async function getCookiesForDownload(video, matchedProfile) {
  if (matchedProfile) {
    return matchedProfile.cookiesText
      ? matchedProfile.cookiesText
      : await extractBrowserCookiesForDomain(matchedProfile.domainPattern);
  }
  // No matched profile: dynamically extract the live browser cookies for the video's exact URL/domain
  return await extractBrowserCookies(video.pageUrl || video.srcUrl || activeTabUrl);
}

/** Wire up all cookie-related button events */
function initCookieUIEvents() {
  // Profile modal: sync cookies button
  if (elements.profSyncCookiesBtn) {
    elements.profSyncCookiesBtn.addEventListener('click', async () => {
      const pattern = elements.profPattern ? elements.profPattern.value.trim() : '';
      if (!pattern) {
        showToast('Enter a domain pattern first.', 'warning');
        return;
      }
      const cookies = await extractBrowserCookiesForDomain(pattern);
      if (elements.profCookies) elements.profCookies.value = cookies;
      showToast(`Synced ${countCookies(cookies)} cookies.`, 'success');
    });
  }
}
