// VideoGrab - popup-cookies.js
// Browser cookie extraction, Netscape format helpers, and cookie status UI

function countCookies(cookieText) {
  if (!cookieText) return 0;
  return cookieText.split('\n').filter(line => {
    const t = line.trim();
    return t && !t.startsWith('#');
  }).length;
}

/** Build Netscape cookie file content from a chrome.cookies array */
function buildNetscapeCookies(cookies, sourceLabel) {
  if (!cookies || cookies.length === 0) return '';
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by VideoGrab',
    `# Source: ${sourceLabel}`
  ];
  cookies.forEach(c => {
    const flag  = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path  = c.path || '/';
    const sec   = c.secure ? 'TRUE' : 'FALSE';
    const exp   = c.expirationDate ? Math.round(c.expirationDate) : 0;
    const prefix = c.httpOnly ? '#HttpOnly_' : '';
    lines.push(`${prefix}${c.domain}\t${flag}\t${path}\t${sec}\t${exp}\t${c.name}\t${c.value}`);
  });
  return lines.join('\n');
}

/** Extract all cookies for a full URL (including HttpOnly via chrome.cookies API) */
async function extractBrowserCookies(pageUrl) {
  if (!pageUrl || !pageUrl.startsWith('http')) return '';
  return new Promise((resolve) => {
    try {
      chrome.cookies.getAll({ url: pageUrl }, (cookies) => {
        resolve(buildNetscapeCookies(cookies || [], pageUrl));
      });
    } catch (e) {
      console.error('[Cookies] extractBrowserCookies error:', e);
      resolve('');
    }
  });
}

/** Extract cookies for a domain pattern (wildcard glob like *.youtube.com) */
async function extractBrowserCookiesForDomain(domainPattern) {
  if (!domainPattern) return '';
  let domain = domainPattern.trim().toLowerCase();
  if (domain.startsWith('*.')) domain = domain.substring(2);
  return new Promise((resolve) => {
    try {
      chrome.cookies.getAll({ domain }, (cookies) => {
        resolve(buildNetscapeCookies(cookies || [], domainPattern));
      });
    } catch (e) {
      console.error('[Cookies] extractBrowserCookiesForDomain error:', e);
      resolve('');
    }
  });
}

/** Refresh the live cookies snapshot for the active tab and update the UI */
async function refreshLiveCookiesState() {
  if (!activeTabUrl || !activeTabUrl.startsWith('http')) {
    updateGlobalCookieStatusUI('', globalCookiesText);
    return;
  }
  liveCookiesText = await extractBrowserCookies(activeTabUrl);
  updateGlobalCookieStatusUI(liveCookiesText, globalCookiesText);
}

function updateGlobalCookieStatusUI(liveText, savedText) {
  const el = elements.globalCookieStatus;
  if (!el) return;
  const dot = el.querySelector('.cookie-status-dot');
  const txt = el.querySelector('.cookie-status-text');

  const liveCount  = countCookies(liveText);
  const savedCount = countCookies(savedText);

  el.className = 'cookie-status-indicator';

  if (!savedText) {
    if (liveCount > 0) {
      el.classList.add('has-cookies');
      txt.innerText = `Live Sync — ${liveCount} active browser cookies`;
    } else {
      el.classList.add('no-cookies');
      txt.innerText = 'Live Sync — no browser cookies detected';
    }
    if (elements.globalCookieMismatchHint) elements.globalCookieMismatchHint.style.display = 'none';
  } else {
    if ((savedText || '').trim() === (liveText || '').trim()) {
      el.classList.add('synced');
      txt.innerText = `Synced — ${savedCount} cookies match browser`;
      if (elements.globalCookieMismatchHint) elements.globalCookieMismatchHint.style.display = 'none';
    } else {
      el.classList.add('override-cookies');
      txt.innerText = `Static Override — ${savedCount} custom cookies saved`;
      if (elements.globalCookieMismatchHint) elements.globalCookieMismatchHint.style.display = 'block';
    }
  }
}

/** Check live cookies for the profile modal's domain pattern */
async function checkModalDomainCookies(pattern) {
  const el = elements.profLiveCookieStatus;
  if (!el) return;
  const txt = el.querySelector('.cookie-status-text');
  if (!pattern) {
    el.className = 'cookie-status-indicator';
    txt.innerText = 'Enter a domain pattern to check';
    return;
  }
  const cookies = await extractBrowserCookiesForDomain(pattern);
  const count = countCookies(cookies);
  el.className = 'cookie-status-indicator';
  if (count > 0) {
    el.classList.add('has-cookies');
    txt.innerText = `${count} live cookies available in browser`;
  } else {
    el.classList.add('no-cookies');
    txt.innerText = 'No live cookies found in browser for this domain';
  }
}

/** Get the cookies to pass to a download job, respecting profile overrides */
async function getCookiesForDownload(video, matchedProfile) {
  if (matchedProfile) {
    return matchedProfile.cookiesText
      ? matchedProfile.cookiesText
      : await extractBrowserCookiesForDomain(matchedProfile.domainPattern);
  }
  return globalCookiesText
    ? globalCookiesText
    : await extractBrowserCookies(video.pageUrl || activeTabUrl);
}

/** Wire up all cookie-related button events in the Global Profile tab */
function initCookieUIEvents() {
  // Toggle editor panel
  if (elements.globalEditCookiesBtn) {
    elements.globalEditCookiesBtn.addEventListener('click', () => {
      const editor = elements.globalCookieEditor;
      const isOpen = editor.classList.contains('open');
      if (!isOpen) {
        editor.querySelector('textarea').value = globalCookiesText || liveCookiesText;
        editor.classList.add('open');
        elements.globalEditCookiesBtn.textContent = 'Close Editor';
      } else {
        editor.classList.remove('open');
        elements.globalEditCookiesBtn.textContent = 'Edit Cookies';
      }
    });
  }

  // Save edited cookies
  const saveEditedBtn = document.getElementById('global-save-edited-cookies-btn');
  if (saveEditedBtn) {
    saveEditedBtn.addEventListener('click', () => {
      const textarea = elements.globalCookieEditor.querySelector('textarea');
      globalCookiesText = textarea.value.trim();
      chrome.storage.local.set({ globalCookiesText }, () => {
        updateGlobalCookieStatusUI(liveCookiesText, globalCookiesText);
        elements.globalCookieEditor.classList.remove('open');
        if (elements.globalEditCookiesBtn) elements.globalEditCookiesBtn.textContent = 'Edit Cookies';
        showToast('Cookies saved.', 'success');
      });
    });
  }

  // Restore to live browser cookies
  if (elements.globalRestoreLiveBtn) {
    elements.globalRestoreLiveBtn.addEventListener('click', async () => {
      globalCookiesText = '';
      chrome.storage.local.set({ globalCookiesText }, () => {
        if (elements.globalCookieEditor) {
          elements.globalCookieEditor.classList.remove('open');
        }
        if (elements.globalEditCookiesBtn) elements.globalEditCookiesBtn.textContent = 'Edit Cookies';
        updateGlobalCookieStatusUI(liveCookiesText, '');
        showToast('Restored to live browser cookies.', 'success');
      });
    });
  }

  // Refresh live cookies status
  if (elements.globalRefreshCookiesBtn) {
    elements.globalRefreshCookiesBtn.addEventListener('click', async () => {
      await refreshLiveCookiesState();
      showToast('Cookie status refreshed.', 'info');
    });
  }

  // Download cookies.txt
  if (elements.globalDownloadCookiesBtn) {
    elements.globalDownloadCookiesBtn.addEventListener('click', async () => {
      const textToDownload = globalCookiesText || liveCookiesText;
      if (!textToDownload) {
        showToast('No cookies to download.', 'warning');
        return;
      }
      const blob = new Blob([textToDownload], { type: 'text/plain' });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement('a');
      a.href     = url;
      a.download = 'cookies.txt';
      a.click();
      URL.revokeObjectURL(url);
    });
  }

  // Upload cookies.txt
  if (elements.globalCookieFile) {
    elements.globalCookieFile.addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (ev) => {
        globalCookiesText = ev.target.result.trim();
        chrome.storage.local.set({ globalCookiesText }, () => {
          updateGlobalCookieStatusUI(liveCookiesText, globalCookiesText);
          showToast(`Uploaded ${countCookies(globalCookiesText)} cookies from file.`, 'success');
        });
      };
      reader.readAsText(file);
      e.target.value = '';
    });
  }

  // Save global User-Agent
  if (elements.saveGlobalProfileBtn) {
    elements.saveGlobalProfileBtn.addEventListener('click', () => {
      globalUserAgent = (elements.globalUa ? elements.globalUa.value : '') || navigator.userAgent;
      chrome.storage.local.set({ globalUserAgent }, () => {
        showToast('Global profile saved.', 'success');
      });
    });
  }

  // Profile modal: sync cookies button
  if (elements.profSyncCookiesBtn) {
    elements.profSyncCookiesBtn.addEventListener('click', async () => {
      const pattern = elements.profPattern ? elements.profPattern.value.trim() : '';
      if (!pattern) {
        showToast('Enter a domain pattern first.', 'warning');
        return;
      }
      const cookies = await extractBrowserCookiesForDomain(pattern);
      if (elements.profCookies) elements.profCookies.value = cookies;
      showToast(`Synced ${countCookies(cookies)} cookies.`, 'success');
    });
  }
}
