// VideoGrab - popup-cookies.js
// Browser cookie extraction, Netscape format helpers, and cookie status UI

function countCookies(cookieText) {
  if (!cookieText) return 0;
  return cookieText.split('\n').filter(line => {
    const t = line.trim();
    return t && !t.startsWith('#');
  }).length;
}

/** Build Netscape cookie file content from a chrome.cookies array */
function buildNetscapeCookies(cookies, sourceLabel) {
  if (!cookies || cookies.length === 0) return '';
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by VideoGrab',
    `# Source: ${sourceLabel}`
  ];
  cookies.forEach(c => {
    const flag  = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path  = c.path || '/';
    const sec   = c.secure ? 'TRUE' : 'FALSE';
    const exp   = c.expirationDate ? Math.round(c.expirationDate) : 0;
    const prefix = c.httpOnly ? '#HttpOnly_' : '';
    lines.push(`${prefix}${c.domain}\t${flag}\t${path}\t${sec}\t${exp}\t${c.name}\t${c.value}`);
  });
  return lines.join('\n');
}

/** Extract all cookies for a full URL (including HttpOnly via chrome.cookies API) */
async function extractBrowserCookies(pageUrl) {
  if (!pageUrl || !pageUrl.startsWith('http')) return '';
  return new Promise((resolve) => {
    try {
      chrome.cookies.getAll({ url: pageUrl }, (cookies) => {
        resolve(buildNetscapeCookies(cookies || [], pageUrl));
      });
    } catch (e) {
      console.error('[Cookies] extractBrowserCookies error:', e);
      resolve('');
    }
  });
}

/** Extract cookies for a domain pattern (wildcard glob like *.youtube.com) */
async function extractBrowserCookiesForDomain(domainPattern) {
  if (!domainPattern) return '';
  let domain = domainPattern.trim().toLowerCase();
  if (domain.startsWith('*.')) domain = domain.substring(2);
  
  const url = `https://${domain}/`;
  
  return new Promise((resolve) => {
    let settled = false;
    const done = (result) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(result);
    };

    const timer = setTimeout(() => {
      console.warn('[Cookies] Timeout extracting cookies for', domainPattern);
      done('');
    }, 5000);

    try {
      chrome.cookies.getAll({ url }, (cookiesByUrl) => {
        if (chrome.runtime.lastError) {
          console.error('[Cookies] getAll url error:', chrome.runtime.lastError.message);
          done('');
          return;
        }
        chrome.cookies.getAll({ domain }, (cookiesByDomain) => {
          if (chrome.runtime.lastError) {
            console.error('[Cookies] getAll domain error:', chrome.runtime.lastError.message);
            done(buildNetscapeCookies(cookiesByUrl || [], domainPattern));
            return;
          }
          const allCookies = [...(cookiesByUrl || [])];
          (cookiesByDomain || []).forEach(c => {
            const exists = allCookies.some(existing => 
              existing.name === c.name && 
              existing.domain === c.domain && 
              existing.path === c.path
            );
            if (!exists) allCookies.push(c);
          });
          done(buildNetscapeCookies(allCookies, domainPattern));
        });
      });
    } catch (e) {
      console.error('[Cookies] extractBrowserCookiesForDomain error:', e);
      done('');
    }
  });
}

/** Refresh the live cookies snapshot for the active tab */
async function refreshLiveCookiesState() {
  if (!activeTabUrl || !activeTabUrl.startsWith('http')) {
    return;
  }
  liveCookiesText = await extractBrowserCookies(activeTabUrl);
}

/** Check live cookies for the profile modal's domain pattern */
async function checkModalDomainCookies(pattern) {
  const el = elements.profLiveCookieStatus;
  if (!el) return;
  const txt = el.querySelector('.cookie-status-text');
  if (!pattern) {
    el.className = 'cookie-status-indicator';
    txt.innerText = 'Enter a domain pattern to check';
    return;
  }
  const cookies = await extractBrowserCookiesForDomain(pattern);
  const count = countCookies(cookies);
  el.className = 'cookie-status-indicator';
  if (count > 0) {
    el.classList.add('has-cookies');
    txt.innerText = `${count} live cookies available in browser`;
  } else {
    el.classList.add('no-cookies');
    txt.innerText = 'No live cookies found in browser for this domain';
  }
}

/** Merge two Netscape cookie strings, deduplicating by name+domain+path */
function mergeNetscapeCookies(textA, textB) {
  if (!textA) return textB || '';
  if (!textB) return textA || '';

  const parseLines = (text) => text.split('\n')
    .filter(l => l.trim() && !l.startsWith('#'))
    .map(l => {
      const parts = l.split('\t');
      if (parts.length < 7) return null;
      return { domain: parts[0], flag: parts[1], path: parts[2], secure: parts[3], exp: parts[4], name: parts[5], value: parts[6] };
    })
    .filter(Boolean);

  const linesA = parseLines(textA);
  const linesB = parseLines(textB);
  const seen = new Set();
  const merged = [];

  linesA.forEach(l => {
    const key = `${l.name}\t${l.domain}\t${l.path}`;
    if (!seen.has(key)) { seen.add(key); merged.push(l); }
  });
  linesB.forEach(l => {
    const key = `${l.name}\t${l.domain}\t${l.path}`;
    if (!seen.has(key)) { seen.add(key); merged.push(l); }
  });

  if (merged.length === 0) return '';
  const header = ['# Netscape HTTP Cookie File', '# Generated by VideoGrab', '# Source: merged'];
  return header.concat(merged.map(l =>
    `${l.domain}\t${l.flag}\t${l.path}\t${l.secure}\t${l.exp}\t${l.name}\t${l.value}`
  )).join('\n');
}

/** Get the cookies to pass to a download job.
 *  Priority: profile saved cookies > profile domain cookies + CDN cookies > page cookies + CDN cookies
 *  Always merges cookies from the video's actual CDN domain so protected content works.
 */
async function getCookiesForDownload(video, matchedProfile) {
  const videoSrcUrl = video.srcUrl || video.pageUrl || '';
  const pageUrl = video.pageUrl || activeTabUrl || '';

  // Determine the "source" cookies (from profile or page)
  let sourceCookies = '';
  if (matchedProfile) {
    sourceCookies = matchedProfile.cookiesText
      ? matchedProfile.cookiesText
      : await extractBrowserCookiesForDomain(matchedProfile.domainPattern);
  } else {
    sourceCookies = await extractBrowserCookies(pageUrl);
  }

  // If the video CDN is on a different domain than the source, also grab CDN cookies
  if (videoSrcUrl && videoSrcUrl.startsWith('http')) {
    try {
      const videoHost = new URL(videoSrcUrl).hostname;
      const pageHost = pageUrl ? new URL(pageUrl).hostname : '';
      if (videoHost && videoHost !== pageHost) {
        const cdnCookies = await extractBrowserCookies(videoSrcUrl);
        if (cdnCookies) {
          sourceCookies = mergeNetscapeCookies(sourceCookies, cdnCookies);
        }
      }
    } catch (e) {
      // URL parse error — skip CDN merge
    }
  }

  return sourceCookies;
}

/** Wire up all cookie-related button events */
function initCookieUIEvents() {
  // Profile modal: sync cookies button
  if (elements.profSyncCookiesBtn) {
    elements.profSyncCookiesBtn.addEventListener('click', async () => {
      const pattern = elements.profPattern ? elements.profPattern.value.trim() : '';
      if (!pattern) {
        showToast('Enter a domain pattern first.', 'warning');
        return;
      }
      const cookies = await extractBrowserCookiesForDomain(pattern);
      if (elements.profCookies) elements.profCookies.value = cookies;
      showToast(`Synced ${countCookies(cookies)} cookies.`, 'success');
    });
  }
}
